name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build-docker:

    runs-on: ubuntu-latest

    steps:
    - name: checkout Code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lidorlg/lidor-python-sce:$(date +%F)-${{ github.run_number }}

    - name: docker login
      run: docker login -u ${{ secrets.dockerhub_user }} -p ${{ secrets.dockerhub_pass }}
      
    - name: docker push
      run: |
        docker push lidorlg/lidor-python-sce:$(date +%F)-${{ github.run_number }}
        docker tag lidorlg/lidor-python-sce:$(date +%F)-${{ github.run_number }} lidorlg/lidor-python-sce:latest
        docker push lidorlg/lidor-python-sce:latest
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Azure Server
        uses: kangketikonlen/ssh-pipeline@v0.0.3
        with:
          # Remote server hostname or IP address.
          host: 172.201.126.44
          # SSH username for the remote server.
          user: github-admin
          # SSH password to authenticate. (Use GitHub secrets!)
          pass: ${{ secrets.AZURE_PASS }} # optional
          # The public host key of the remote server to prevent MITM attacks. (Use GitHub secrets!)
          known_hosts: ${{ secrets.PUB_KEY }}
          # Multiline block of commands to run before the SCP transfer.
          first_ssh: echo "hello" # optional

          last_ssh: ls / # optional
